@baseUrl = http://localhost:3334

@authToken = {{ login.response.body.token }}

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "deyvison.costa1@gmail.com",
    "password": "Deyvison@1234"
}
###

# @name createCustomer
POST {{baseUrl}}/customers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Joaquim da Silva",
    "email": "joaquim.silvsa@gmail.com",
    "cpf": "12345678711",
    "phone": "11987654321",
    "zipCode": "12345678",
    "street": "Rua Exemplo",
    "number": "123",
    "complement": "Apto 456",
    "city": "São Paulo",
    "state": "SP"
}
###

# @name updateCustomer
PUT {{baseUrl}}/customers/a62374f2-6658-48b0-861a-c621d6eeb826
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Joaquim Medeiros",
    "email": "joaquim.medeiross@gmail.com",
    "cpf": "12345678711",
    "phone": "11987654321",
    "zipCode": "12345678",
    "street": "Rua Exemplo",
    "number": "123",
    "complement": "Apto 456",
    "city": "São Paulo",
    "state": "SP"
}
###

# @name fetchCustomers
GET {{baseUrl}}/customers
Authorization: Bearer {{authToken}}
###

# @name deleteCustomer
DELETE {{baseUrl}}/customers/a62374f2-6658-48b0-861a-c621d6eeb826
Authorization: Bearer {{authToken}}
###

# @name fetchCustomerId
GET {{baseUrl}}/customers/a62374f2-6658-48b0-861a-c621d6eeb826
Authorization: Bearer {{authToken}}
###