@baseUrl = http://localhost:3334

@authToken = {{ login.response.body.token }}

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "john.costa5@gmail.com",
    "password": "John@1234"
}
###

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Costa5",
    "email": "john.costa5@gmail.com",
    "password": "John@1234"
}